version: "2"

services:
  web:
    image: goalgorilla/open_social_docker:dev
    volumes:
     - ./:/var/www
    links:
     - db
     - mailcatcher
    environment:
     - DRUPAL_SETTINGS=development
    network_mode: "bridge"
    container_name: social_web
    labels:
      - 'traefik.backend=web'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:eegage-social.dev'

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
      - db_data:/var/lib/mysql
    network_mode: "bridge"
    container_name: social_db
    command: mysqld --max_allowed_packet=16M

  mailcatcher:
    image: schickling/mailcatcher
    network_mode: "bridge"
    container_name: social_mailcatcher
    labels:
      - 'traefik.backend=mailcatcher'
      - 'traefik.port=1080'
      - 'traefik.frontend.rule=Host:mailcatcher.eegage-social.dev'

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    links:
     - web:web
    ports:
     - "4444"
     - "5900"
    cap_add:
     - NET_ADMIN
     - NET_RAW
    network_mode: "bridge"
    container_name: social_selenium

  behat:
    image: goalgorilla/open_social_docker:dev
    volumes:
     - ./:/var/www
    links:
     - web:web
     - db:db
     - selenium:selenium
    environment:
     - DRUPAL_SETTINGS=development
    network_mode: "bridge"
    container_name: social_behat

  cron:
    image: goalgorilla/open_social_docker:cron
    volumes:
     - ./:/var/www
    links:
     - db
     - mailcatcher
    environment:
     - DRUPAL_SETTINGS=development
    network_mode: "bridge"
    container_name: social_cron

volumes:
  db_data:
